# Generated by Django 5.2.9 on 2025-12-25 09:56

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_productcode_default_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='거래처코드')),
                ('name', models.CharField(max_length=200, verbose_name='거래처명')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='영문명')),
                ('address', models.TextField(blank=True, null=True, verbose_name='주소')),
                ('ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='팩스번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자명')),
                ('manager_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='담당자 연락처')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='담당자 이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처',
                'db_table': 'voucher_customer',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('template_type', models.CharField(choices=[('QUOTE', '견적서'), ('INVOICE', '청구서'), ('DELIVERY', '납품서'), ('PRICE_LIST', '단가표'), ('CONTRACT', '계약서')], max_length=20, verbose_name='템플릿 유형')),
                ('filename', models.CharField(help_text='docx_templates/ 폴더 내 파일명', max_length=200, verbose_name='파일명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('is_default', models.BooleanField(default=False, help_text='해당 유형의 기본 템플릿으로 사용', verbose_name='기본 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '문서 템플릿',
                'verbose_name_plural': '문서 템플릿',
                'db_table': 'voucher_document_template',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(help_text='예: QT-2026-0001', max_length=50, unique=True, verbose_name='견적번호')),
                ('title', models.CharField(max_length=200, verbose_name='견적건명')),
                ('quote_date', models.DateField(default=datetime.date.today, verbose_name='견적일자')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='유효기간')),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('SENT', '발송완료'), ('ACCEPTED', '수락'), ('REJECTED', '거절'), ('EXPIRED', '만료')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='수신처 주소')),
                ('customer_ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='수신처 대표자')),
                ('customer_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='수신처 연락처')),
                ('customer_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='수신처 담당자')),
                ('customer_manager_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='수신처 담당자 연락처')),
                ('customer_manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='수신처 담당자 이메일')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='공급처명')),
                ('supplier_address', models.TextField(blank=True, null=True, verbose_name='공급처 주소')),
                ('supplier_ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='공급처 대표자')),
                ('supplier_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='공급처 TEL')),
                ('supplier_fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='공급처 FAX')),
                ('supplier_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='공급처 담당자')),
                ('supplier_manager_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='공급처 담당자 연락처')),
                ('supplier_manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='공급처 담당자 이메일')),
                ('valid_period', models.CharField(blank=True, max_length=200, null=True, verbose_name='적용기간')),
                ('trade_terms', models.TextField(blank=True, null=True, verbose_name='거래조건')),
                ('bank_account', models.TextField(blank=True, null=True, verbose_name='결제계좌')),
                ('default_currency', models.CharField(choices=[('KRW', '원 (₩)'), ('JPY', '엔 (¥)'), ('USD', '달러 ($)'), ('CNY', '위안 (¥)')], default='KRW', max_length=10, verbose_name='기본 통화')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='총 금액')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='voucher.customer', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '견적서',
                'verbose_name_plural': '견적서',
                'db_table': 'voucher_quote',
                'ordering': ['-quote_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=1, verbose_name='순번')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='구분')),
                ('gas_name', models.CharField(blank=True, help_text='제품코드에서 자동 입력 또는 직접 입력', max_length=100, null=True, verbose_name='가스명')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='품명')),
                ('material_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='자재코드')),
                ('end_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='End User')),
                ('packing', models.CharField(blank=True, help_text='예: 47L, Y-1', max_length=100, null=True, verbose_name='포장')),
                ('filling_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='충전중량 (kg)')),
                ('currency', models.CharField(choices=[('KRW', '원 (₩)'), ('JPY', '엔 (¥)'), ('USD', '달러 ($)'), ('CNY', '위안 (¥)')], default='KRW', max_length=10, verbose_name='통화')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='단가 (1kg)')),
                ('packing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='포장단가')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcode', verbose_name='제품코드')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='voucher.quote', verbose_name='견적서')),
            ],
            options={
                'verbose_name': '견적 품목',
                'verbose_name_plural': '견적 품목',
                'db_table': 'voucher_quote_item',
                'ordering': ['seq'],
            },
        ),
    ]
