# Generated by Django 5.2.9 on 2025-12-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='회사코드')),
                ('name', models.CharField(max_length=200, verbose_name='회사명')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='영문명')),
                ('name_jp', models.CharField(blank=True, max_length=200, null=True, verbose_name='일문명')),
                ('is_supplier', models.BooleanField(default=False, help_text='체크하면 공급처(자사)로 사용', verbose_name='자사 여부')),
                ('is_customer', models.BooleanField(default=True, help_text='체크하면 거래처로 사용', verbose_name='거래처 여부')),
                ('address', models.TextField(blank=True, null=True, verbose_name='주소')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='영문 주소')),
                ('ceo', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자')),
                ('business_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='사업자등록번호')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='팩스번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자명')),
                ('manager_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='담당자 연락처')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='담당자 이메일')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='은행명')),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='계좌번호')),
                ('bank_holder', models.CharField(blank=True, max_length=100, null=True, verbose_name='예금주')),
                ('default_trade_terms', models.TextField(blank=True, null=True, verbose_name='기본 거래조건')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '회사정보',
                'verbose_name_plural': '회사정보',
                'db_table': 'voucher_company_info',
                'ordering': ['-is_supplier', 'name'],
            },
        ),
    ]
