# Generated by Django 5.2.9 on 2025-12-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='packing',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='용량 (L)'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='cylinder_spec',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='용기 스펙'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='valve_spec',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='밸브 스펙'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='filling_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='충전량 (kg)'),
        ),
    ]
