# Generated by Django 5.2.9 on 2025-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='field_type',
            field=models.CharField(choices=[('gas_name', '가스명'), ('valve_spec', '밸브 스펙'), ('cylinder_spec', '용기 스펙'), ('usage_place', '사용처'), ('location', '위치')], db_index=True, help_text='번역할 필드의 타입', max_length=50, verbose_name='필드 타입'),
        ),
        migrations.CreateModel(
            name='EndUserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_enduser_code', models.CharField(default='SDC', max_length=50, verbose_name='기본 EndUser 코드')),
                ('default_enduser_name', models.CharField(default='SDC', max_length=100, verbose_name='기본 EndUser 명')),
                ('cylinder_type_key', models.CharField(blank=True, help_text='NULL이면 기본값, 값이 있으면 예외 규칙', max_length=32, null=True, verbose_name='용기종류 키')),
                ('gas_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='가스명')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='용량')),
                ('valve_spec', models.CharField(blank=True, max_length=180, null=True, verbose_name='밸브 스펙')),
                ('cylinder_spec', models.CharField(blank=True, max_length=180, null=True, verbose_name='용기 스펙')),
                ('usage_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용처')),
                ('exception_enduser_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='예외 EndUser 코드')),
                ('exception_enduser_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='예외 EndUser 명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
            ],
            options={
                'verbose_name': 'EndUser 정책',
                'verbose_name_plural': 'EndUser 정책',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['cylinder_type_key'], name='idx_enduser_policy_type_key'), models.Index(condition=models.Q(('cylinder_type_key__isnull', True), ('is_active', True)), fields=['gas_name', 'capacity'], name='idx_enduser_policy_gas')],
            },
        ),
        migrations.CreateModel(
            name='ValveAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_valve_spec', models.CharField(help_text='FCMS 원본 값', max_length=180, verbose_name='원본 밸브 스펙')),
                ('standard_valve_spec', models.CharField(help_text='대시보드 표시용', max_length=180, verbose_name='표준 밸브 스펙')),
                ('valve_group_code', models.CharField(blank=True, help_text='통합 그룹 식별', max_length=50, null=True, verbose_name='밸브 그룹 코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('priority', models.IntegerField(default=0, help_text='낮을수록 우선', verbose_name='우선순위')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '밸브 표준화',
                'verbose_name_plural': '밸브 표준화',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['raw_valve_spec'], name='idx_valve_alias_raw'), models.Index(condition=models.Q(('is_active', True)), fields=['standard_valve_spec'], name='idx_valve_alias_standard')],
                'unique_together': {('raw_valve_spec', 'is_active')},
            },
        ),
    ]
