# Generated by Django 5.2.9 on 2025-12-24 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFillingMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='YYYY-MM-01 형식')),
                ('cylinder_type_key', models.CharField(db_index=True, max_length=32)),
                ('gas_name', models.CharField(db_index=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('valve_spec', models.CharField(blank=True, max_length=200, null=True)),
                ('cylinder_spec', models.CharField(blank=True, max_length=200, null=True)),
                ('usage_place', models.CharField(blank=True, max_length=100, null=True)),
                ('planned_fill_qty', models.IntegerField(default=0, help_text='월 충전 계획 수량', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_shutdown', models.BooleanField(default=False, help_text='오버홀/셧다운 여부 (True면 충전 불가)')),
                ('note', models.TextField(blank=True, help_text='예: 4월 전체 오버홀', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '충전 계획',
                'verbose_name_plural': '충전 계획',
                'db_table': 'plan_filling_monthly',
                'indexes': [models.Index(fields=['month', 'cylinder_type_key'], name='plan_fillin_month_845fd4_idx'), models.Index(fields=['gas_name', 'capacity'], name='plan_fillin_gas_nam_6dfdb3_idx')],
                'unique_together': {('month', 'cylinder_type_key')},
            },
        ),
    ]
