# Generated by Django 4.2.27 on 2025-12-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylinders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylindermemo',
            name='password',
            field=models.CharField(default='0000', help_text='4자리 숫자', max_length=4, verbose_name='암호'),
        ),
    ]
