# Generated by Django 5.2.9 on 2025-12-26 12:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_productcode_default_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_hour', models.IntegerField(default=18, help_text='일간 스냅샷 기준 시간 (0-23)', verbose_name='마감 시간 (시)')),
                ('cutoff_minute', models.IntegerField(default=0, help_text='일간 스냅샷 기준 분 (0-59)', verbose_name='마감 시간 (분)')),
                ('low_stock_threshold_cylinder', models.IntegerField(default=5, help_text='용기 종류별 최소 재고 수량', verbose_name='용기 저재고 임계값')),
                ('low_stock_threshold_product_kg', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='제품별 최소 재고량', max_digits=10, verbose_name='제품 저재고 임계값 (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '재고 설정',
                'verbose_name_plural': '재고 설정',
                'db_table': 'inventory_settings',
            },
        ),
        migrations.CreateModel(
            name='CylinderInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_type_key', models.CharField(db_index=True, help_text='cy_cylinder_current.dashboard_cylinder_type_key 또는 직접 정의', max_length=50, verbose_name='용기종류키')),
                ('gas_name', models.CharField(blank=True, max_length=100, verbose_name='가스명')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='용량')),
                ('valve_spec', models.CharField(blank=True, max_length=200, verbose_name='밸브 스펙')),
                ('cylinder_spec', models.CharField(blank=True, max_length=200, verbose_name='용기 스펙')),
                ('enduser_code', models.CharField(blank=True, max_length=50, verbose_name='엔드유저 코드')),
                ('status', models.CharField(choices=[('EMPTY', '빈 용기'), ('FILLED', '충전 용기'), ('FILLING', '충전 중'), ('ANALYZING', '분석 중'), ('REPAIRING', '수리 중'), ('AT_CUSTOMER', '고객 보유'), ('IN_TRANSIT', '운송 중'), ('SCRAPPED', '폐기'), ('OTHER', '기타')], db_index=True, max_length=20, verbose_name='상태')),
                ('location', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='위치')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량 (병)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
            ],
            options={
                'verbose_name': '용기 재고',
                'verbose_name_plural': '용기 재고',
                'db_table': 'cylinder_inventory',
                'indexes': [models.Index(fields=['gas_name', 'status'], name='cylinder_in_gas_nam_953f32_idx'), models.Index(fields=['status', 'location'], name='cylinder_in_status_5a63e9_idx')],
                'unique_together': {('cylinder_type_key', 'status', 'location')},
            },
        ),
        migrations.CreateModel(
            name='CylinderInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='스냅샷 일자')),
                ('snapshot_datetime', models.DateTimeField(help_text='실제 스냅샷 생성 시점', verbose_name='스냅샷 시각')),
                ('cylinder_type_key', models.CharField(db_index=True, max_length=50, verbose_name='용기종류키')),
                ('gas_name', models.CharField(blank=True, max_length=100, verbose_name='가스명')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='용량')),
                ('valve_spec', models.CharField(blank=True, max_length=200, verbose_name='밸브 스펙')),
                ('cylinder_spec', models.CharField(blank=True, max_length=200, verbose_name='용기 스펙')),
                ('enduser_code', models.CharField(blank=True, max_length=50, verbose_name='엔드유저 코드')),
                ('status', models.CharField(db_index=True, max_length=20, verbose_name='상태')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량 (병)')),
                ('day_in', models.IntegerField(default=0, verbose_name='당일 입고')),
                ('day_out', models.IntegerField(default=0, verbose_name='당일 출고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '용기 재고 스냅샷',
                'verbose_name_plural': '용기 재고 스냅샷',
                'db_table': 'cylinder_inventory_snapshot',
                'ordering': ['-snapshot_date', 'cylinder_type_key'],
                'indexes': [models.Index(fields=['snapshot_date', 'gas_name'], name='cylinder_in_snapsho_5b31e0_idx'), models.Index(fields=['snapshot_date', 'status'], name='cylinder_in_snapsho_74b62f_idx')],
                'unique_together': {('snapshot_date', 'cylinder_type_key', 'status', 'location')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_no', models.CharField(help_text='자동 생성: INV-YYYYMMDD-NNNN', max_length=50, unique=True, verbose_name='트랜잭션번호')),
                ('txn_type', models.CharField(choices=[('CYL_IN', '용기 입고'), ('CYL_OUT', '용기 출고'), ('CYL_RETURN', '용기 회수'), ('CYL_FILL', '용기 충전'), ('CYL_TRANSFER', '용기 이동'), ('CYL_ADJ', '용기 조정'), ('PROD_IN', '제품 입고'), ('PROD_OUT', '제품 출하'), ('PROD_ADJ', '제품 조정'), ('SNAPSHOT', '스냅샷')], max_length=20, verbose_name='트랜잭션 유형')),
                ('txn_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='재고 반영 기준일', verbose_name='거래일')),
                ('txn_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='정확한 거래 시점', verbose_name='거래일시')),
                ('cylinder_no', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='용기번호')),
                ('cylinder_type_key', models.CharField(blank=True, db_index=True, help_text='cy_cylinder_current.dashboard_cylinder_type_key', max_length=50, verbose_name='용기종류키')),
                ('gas_name', models.CharField(blank=True, max_length=100, verbose_name='가스명')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='용기: 개수, 가스: kg', max_digits=12, verbose_name='수량')),
                ('is_inbound', models.BooleanField(default=True, help_text='True: 재고 증가, False: 재고 감소', verbose_name='입고여부')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='이전 상태')),
                ('to_status', models.CharField(blank=True, max_length=30, verbose_name='이후 상태')),
                ('from_location', models.CharField(blank=True, max_length=100, verbose_name='이전 위치')),
                ('to_location', models.CharField(blank=True, max_length=100, verbose_name='이후 위치')),
                ('reference_type', models.CharField(blank=True, help_text='PO, MOVE_REPORT, ARRIVAL_SHIPPING 등', max_length=50, verbose_name='참조문서유형')),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='참조문서번호')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='products.productcode', verbose_name='제품코드')),
            ],
            options={
                'verbose_name': '재고 트랜잭션',
                'verbose_name_plural': '재고 트랜잭션',
                'db_table': 'inventory_transaction',
                'ordering': ['-txn_datetime', '-id'],
                'indexes': [models.Index(fields=['txn_date', 'txn_type'], name='inventory_t_txn_dat_7e0050_idx'), models.Index(fields=['cylinder_no', '-txn_datetime'], name='inventory_t_cylinde_d8e1fe_idx'), models.Index(fields=['gas_name', '-txn_datetime'], name='inventory_t_gas_nam_ba2d16_idx'), models.Index(fields=['reference_type', 'reference_no'], name='inventory_t_referen_24eaf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_condition_code', models.CharField(db_index=True, help_text='예: KF001, KF013', max_length=100, verbose_name='제품코드')),
                ('gas_name', models.CharField(blank=True, max_length=100, verbose_name='가스명')),
                ('warehouse', models.CharField(db_index=True, default='MAIN', help_text='창고 위치 (기본: MAIN)', max_length=100, verbose_name='창고')),
                ('quantity', models.IntegerField(default=0, help_text='창고 내 충전 용기 수', validators=[django.core.validators.MinValueValidator(0)], verbose_name='재고수량 (병)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='products.productcode', verbose_name='제품코드')),
            ],
            options={
                'verbose_name': '제품 재고',
                'verbose_name_plural': '제품 재고',
                'db_table': 'product_inventory',
                'indexes': [models.Index(fields=['trade_condition_code'], name='product_inv_trade_c_9c3008_idx'), models.Index(fields=['gas_name'], name='product_inv_gas_nam_3b2686_idx')],
                'unique_together': {('trade_condition_code', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='ProductInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='스냅샷 일자')),
                ('snapshot_datetime', models.DateTimeField(verbose_name='스냅샷 시각')),
                ('trade_condition_code', models.CharField(db_index=True, max_length=100, verbose_name='제품코드')),
                ('gas_name', models.CharField(blank=True, max_length=100, verbose_name='가스명')),
                ('warehouse', models.CharField(default='MAIN', max_length=100, verbose_name='창고')),
                ('quantity', models.IntegerField(default=0, verbose_name='재고수량 (병)')),
                ('day_in', models.IntegerField(default=0, verbose_name='당일 입고 (병)')),
                ('day_out', models.IntegerField(default=0, verbose_name='당일 출하 (병)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshots', to='products.productcode', verbose_name='제품코드')),
            ],
            options={
                'verbose_name': '제품 재고 스냅샷',
                'verbose_name_plural': '제품 재고 스냅샷',
                'db_table': 'product_inventory_snapshot',
                'ordering': ['-snapshot_date', 'trade_condition_code'],
                'indexes': [models.Index(fields=['snapshot_date', 'trade_condition_code'], name='product_inv_snapsho_c03041_idx')],
                'unique_together': {('snapshot_date', 'trade_condition_code', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='SnapshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='스냅샷 일자')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('status', models.CharField(choices=[('RUNNING', '진행중'), ('SUCCESS', '성공'), ('FAILED', '실패'), ('PARTIAL', '일부성공')], default='RUNNING', max_length=20, verbose_name='상태')),
                ('cylinder_snapshots_created', models.IntegerField(default=0, verbose_name='용기 스냅샷 수')),
                ('product_snapshots_created', models.IntegerField(default=0, verbose_name='제품 스냅샷 수')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('triggered_by', models.CharField(blank=True, help_text='AUTO: 자동, MANUAL: 수동', max_length=50, verbose_name='트리거')),
                ('triggered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
            ],
            options={
                'verbose_name': '스냅샷 로그',
                'verbose_name_plural': '스냅샷 로그',
                'db_table': 'inventory_snapshot_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['snapshot_date', 'status'], name='inventory_s_snapsho_1193a3_idx')],
            },
        ),
    ]
