# Generated by Django 5.2.9 on 2025-12-27 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysettings',
            name='cutoff_hour',
            field=models.IntegerField(default=0, help_text='일간 스냅샷 기준 시간 (0-23), 0 = 자정', verbose_name='마감 시간 (시)'),
        ),
        migrations.CreateModel(
            name='CylinderMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_no', models.CharField(db_index=True, max_length=20, verbose_name='용기번호')),
                ('event_type', models.CharField(choices=[('OUT', '정비출고'), ('IN', '정비입고')], db_index=True, max_length=10, verbose_name='구분')),
                ('event_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='일자')),
                ('vendor_name', models.CharField(blank=True, help_text='외주처/정비업체명', max_length=200, verbose_name='정비처')),
                ('reference_no', models.CharField(blank=True, db_index=True, help_text='내부 문서번호/전표번호 등', max_length=100, verbose_name='참조번호')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cylinder_maintenance_logs', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '정비 입출고 로그',
                'verbose_name_plural': '정비 입출고 로그',
                'db_table': 'cylinder_maintenance_log',
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['cylinder_no', '-event_date'], name='cylinder_ma_cylinde_49ae79_idx'), models.Index(fields=['event_type', '-event_date'], name='cylinder_ma_event_t_943f94_idx')],
            },
        ),
    ]
