# Generated by Django 4.2.10 on 2025-12-14 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('WEEKLY', '주간'), ('MONTHLY', '월간'), ('HISTORY_EXPORT', '이력 내보내기')], db_index=True, max_length=20)),
                ('params_json', models.JSONField(default=dict, help_text='필터/기간 등 파라미터')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보고서 출력 이력',
                'verbose_name_plural': '보고서 출력 이력',
                'db_table': 'report_export_log',
                'ordering': ['-exported_at'],
            },
        ),
    ]
