"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--%&9(@trtd#1y@4q-_4!45vrk@4d65y^e-9n!&0&ppm$*+6em7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # 숫자 포맷팅 (intcomma 등)
    # CYNOW apps
    'core.apps.CoreConfig',
    'dashboard',
    'plans',
    'history',
    'reports',
    'cylinders',
    'alerts',
    'orders',
    'devices',
    'simulation',
    'products',
    'voucher',  # 전표/견적서 생성
    'inventory',  # 재고 관리
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Phase 1: SQLite for development
# Phase 2: PostgreSQL for production
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite3')

# 'postgres' 또는 'postgresql' 모두 허용
if DB_ENGINE in ('postgresql', 'postgres'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'cycy_db'),  # CDC 데이터와 같은 DB 사용
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'options': '-c search_path=public,fcms_cdc'  # 스키마 검색 경로 설정
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# =============================================================================
# 서브패스 배포 설정 (/cynow/)
# =============================================================================
# NGINX 리버스 프록시 환경에서 /cynow/ 경로로 서비스
# 환경변수로 제어: 로컬 개발 시에는 설정하지 않음

# 서브패스 설정 (환경변수에서 읽음, 없으면 None)
FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME', None)

# NGINX에서 X-Forwarded-Host 헤더를 신뢰
USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', 'False') == 'True'

# CSRF 신뢰 출처
_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [x.strip() for x in _csrf_origins.split(',') if x.strip()] if _csrf_origins else []

# 쿠키 경로 (서브패스 사용 시 설정)
SESSION_COOKIE_PATH = os.getenv('SESSION_COOKIE_PATH', '/')
CSRF_COOKIE_PATH = os.getenv('CSRF_COOKIE_PATH', '/')


# =============================================================================
# Static files (CSS, JavaScript, Images)
# =============================================================================
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 서브패스가 있으면 포함, 없으면 기본값
_script_name = os.getenv('FORCE_SCRIPT_NAME', '')
STATIC_URL = f'{_script_name}/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 미디어 파일
MEDIA_URL = f'{_script_name}/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# Login URLs
# =============================================================================
# URL 이름을 사용하면 FORCE_SCRIPT_NAME이 자동으로 적용됨
LOGIN_URL = 'login'
_default_root = f'{_script_name}/' if _script_name else '/'
LOGIN_REDIRECT_URL = os.getenv('LOGIN_REDIRECT_URL', _default_root)
LOGOUT_REDIRECT_URL = os.getenv('LOGOUT_REDIRECT_URL', _default_root)
