# Generated by Django 5.2.9 on 2025-12-18 15:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_order_no', models.CharField(help_text='유일한 PO 식별자 - 고객이 발행한 발주서 번호', max_length=100, unique=True, verbose_name='PO번호(고객발주번호)')),
                ('supplier_user_code', models.CharField(help_text='FCMS 거래처 코드', max_length=50, verbose_name='고객코드')),
                ('supplier_user_name', models.CharField(blank=True, max_length=200, verbose_name='고객명')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='수주일시')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('GUIDED', '번호가이드생성'), ('MATCHED', 'FCMS매칭완료'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '수주',
                'verbose_name_plural': '수주',
                'db_table': 'po_simple',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MoveNoGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_move_no', models.CharField(help_text='FP+YY+6자리 (예: FP250001) - 참고용', max_length=50, verbose_name='추천이동서번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('state', models.CharField(choices=[('SHOWN', '표시됨'), ('MATCHED', 'FCMS매칭'), ('IGNORED', '사용안함')], default='SHOWN', max_length=20, verbose_name='상태')),
                ('fcms_actual_move_no', models.CharField(blank=True, help_text='TR_MOVE_REPORTS.MOVE_REPORT_NO', max_length=50, verbose_name='FCMS실제번호')),
                ('fcms_matched_at', models.DateTimeField(blank=True, null=True, verbose_name='FCMS매칭일시')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_guides', to='orders.po', verbose_name='수주')),
            ],
            options={
                'verbose_name': '이동서번호가이드',
                'verbose_name_plural': '이동서번호가이드',
                'db_table': 'move_no_guide',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMSMatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcms_arrival_shipping_no', models.CharField(blank=True, help_text='TR_ORDERS.ARRIVAL_SHIPPING_NO', max_length=50, verbose_name='FCMS도착출하번호')),
                ('fcms_move_report_no', models.CharField(blank=True, help_text='TR_MOVE_REPORTS.MOVE_REPORT_NO', max_length=50, verbose_name='FCMS이동서번호')),
                ('match_state', models.CharField(choices=[('MATCHED', 'FCMS매칭완료'), ('NOT_ENTERED', '미입력'), ('MISMATCH', '번호불일치')], default='NOT_ENTERED', max_length=20, verbose_name='매칭상태')),
                ('last_checked_at', models.DateTimeField(auto_now=True, verbose_name='최종확인일시')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fcms_match_status', to='orders.po', verbose_name='수주')),
            ],
            options={
                'verbose_name': 'FCMS매칭상태',
                'verbose_name_plural': 'FCMS매칭상태',
                'db_table': 'fcms_match_status',
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(verbose_name='라인번호')),
                ('trade_condition_code', models.CharField(help_text='FCMS 품목 코드', max_length=100, verbose_name='제품코드')),
                ('trade_condition_name', models.CharField(blank=True, max_length=200, verbose_name='제품명')),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='수주수량')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.po', verbose_name='수주')),
            ],
            options={
                'verbose_name': '수주품목',
                'verbose_name_plural': '수주품목',
                'db_table': 'po_item_simple',
                'ordering': ['po', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='po',
            index=models.Index(fields=['customer_order_no'], name='po_simple_custome_f36e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='po',
            index=models.Index(fields=['status'], name='po_simple_status_a53d89_idx'),
        ),
        migrations.AddIndex(
            model_name='po',
            index=models.Index(fields=['supplier_user_code'], name='po_simple_supplie_24ef04_idx'),
        ),
        migrations.AddIndex(
            model_name='movenoguide',
            index=models.Index(fields=['po', 'state'], name='move_no_gui_po_id_b32264_idx'),
        ),
        migrations.AddIndex(
            model_name='movenoguide',
            index=models.Index(fields=['suggested_move_no'], name='move_no_gui_suggest_615ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='poitem',
            index=models.Index(fields=['trade_condition_code'], name='po_item_sim_trade_c_ed58af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poitem',
            unique_together={('po', 'line_no')},
        ),
    ]
