# Generated by Django 5.2.9 on 2025-12-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0005_alter_productcode_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='currency',
            field=models.CharField(choices=[('KRW', '원 (₩)'), ('JPY', '엔 (¥)'), ('USD', '달러 ($)'), ('CNY', '위안 (¥)')], default='KRW', max_length=10, verbose_name='통화'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='cylinder_spec',
            field=models.CharField(blank=True, max_length=200, verbose_name='용기스펙'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='filling_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='충전량(kg)'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='gas_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='가스명'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='product_code',
            field=models.ForeignKey(blank=True, help_text='ProductCode 테이블 FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='products.productcode', verbose_name='제품코드 참조'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg당 단가', max_digits=12, null=True, verbose_name='단가(/kg)'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='valve_spec',
            field=models.CharField(blank=True, max_length=200, verbose_name='밸브스펙'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='trade_condition_code',
            field=models.CharField(help_text='FCMS 품목 코드 (예: KF001)', max_length=100, verbose_name='제품코드'),
        ),
    ]
