# Generated by Django 5.2.9 on 2025-12-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_improve_poitem_with_productcode'),
        ('voucher', '0003_add_quote_item_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='고객사 선택 (CompanyInfo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='voucher.companyinfo', verbose_name='고객사'),
        ),
        migrations.AddField(
            model_name='po',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='지정일 납기일 때만 입력', null=True, verbose_name='납기일'),
        ),
        migrations.AddField(
            model_name='po',
            name='delivery_type',
            field=models.CharField(choices=[('PARTIAL', '분납 (익월말까지)'), ('FIXED', '지정일')], default='PARTIAL', help_text='분납: 익월말까지 / 지정일: 특정일 지정', max_length=20, verbose_name='납기유형'),
        ),
        migrations.AlterField(
            model_name='po',
            name='supplier_user_code',
            field=models.CharField(blank=True, help_text='FCMS 거래처 코드', max_length=50, verbose_name='고객코드'),
        ),
    ]
