# Generated by Django 5.2.9 on 2025-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_customer_and_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='po',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='poitem',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='비워두면 분납(익월말), 날짜 입력 시 해당일 납기', null=True, verbose_name='납기일'),
        ),
    ]
