# Generated by Django 5.2.9 on 2025-12-25 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_move_delivery_to_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='received_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='수주일'),
        ),
    ]
