# Generated by Django 5.2.9 on 2025-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_change_received_at_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitem',
            name='line_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='라인번호'),
        ),
    ]
