# Generated by Django 5.2.9 on 2025-12-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_make_line_no_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poitem',
            unique_together=set(),
        ),
    ]
