# Generated by Django - FCMSProductionProgress 모델 추가 (간소화 버전)
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMSProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_shipping_no', models.CharField(max_length=50, verbose_name='도착출하번호')),
                ('item_name', models.CharField(blank=True, max_length=200, verbose_name='품목명')),
                ('packing_name', models.CharField(blank=True, max_length=200, verbose_name='포장명')),
                ('trade_condition_code', models.CharField(blank=True, max_length=100, verbose_name='거래조건코드')),
                ('selection_pattern_code', models.CharField(blank=True, max_length=100, verbose_name='선택패턴코드')),
                ('instruction_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='지시수량(kg)')),
                ('instruction_count', models.IntegerField(default=0, verbose_name='지시횟수(병)')),
                ('filling_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='충전임계값')),
                ('filled_count', models.IntegerField(default=0, verbose_name='충전완료(병)')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='동기화일시')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_progress', to='orders.po', verbose_name='수주')),
            ],
            options={
                'verbose_name': 'FCMS생산진척',
                'verbose_name_plural': 'FCMS생산진척',
                'db_table': 'fcms_production_progress',
                'ordering': ['po', 'arrival_shipping_no'],
            },
        ),
        migrations.AddIndex(
            model_name='fcmsproductionprogress',
            index=models.Index(fields=['arrival_shipping_no'], name='fcms_produc_arrival_7c7b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmsproductionprogress',
            index=models.Index(fields=['po', 'arrival_shipping_no'], name='fcms_produc_po_id_a1a9e2_idx'),
        ),
    ]

