# Generated by Django - PlannedMoveReport 모델 추가 (가발행 이동서)
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_add_fcms_production_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMoveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # 가발행 정보
                ('planned_move_no', models.CharField(help_text='CYNOW에서 추천/입력한 이동서번호 (예: FP250001)', max_length=50, verbose_name='가발행번호')),
                ('sequence', models.IntegerField(default=1, help_text='해당 수주의 N번째 이동서', verbose_name='순번')),
                # 품목 정보
                ('trade_condition_code', models.CharField(blank=True, max_length=100, verbose_name='제품코드')),
                ('gas_name', models.CharField(blank=True, max_length=100, verbose_name='가스명')),
                # 수량
                ('planned_qty', models.IntegerField(default=0, help_text='이 이동서로 발행할 수량', verbose_name='계획수량(병)')),
                ('planned_weight', models.DecimalField(blank=True, decimal_places=2, help_text='수량 × 충전량', max_digits=10, null=True, verbose_name='계획중량(kg)')),
                # 일정
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='발행예정일')),
                ('filling_plan_date', models.DateField(blank=True, null=True, verbose_name='충전계획일')),
                ('shipping_plan_date', models.DateField(blank=True, null=True, verbose_name='출하계획일')),
                # 상태
                ('status', models.CharField(choices=[('PLANNED', '가발행'), ('PENDING', '입력대기'), ('MATCHED', 'FCMS매칭'), ('MISMATCH', '불일치'), ('CANCELLED', '취소')], default='PLANNED', max_length=20, verbose_name='상태')),
                # FCMS 매칭
                ('fcms_matched_no', models.CharField(blank=True, help_text='CDC에서 확인된 실제 이동서번호', max_length=50, verbose_name='FCMS매칭번호')),
                ('fcms_matched_at', models.DateTimeField(blank=True, null=True, verbose_name='매칭일시')),
                ('fcms_instruction_count', models.IntegerField(default=0, help_text='CDC에서 확인된 실제 지시 수량', verbose_name='FCMS지시수량')),
                # 메모
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                # 타임스탬프
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                # FK
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_moves', to='orders.po', verbose_name='수주')),
                ('po_item', models.ForeignKey(blank=True, help_text='연결된 수주품목 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_moves', to='orders.poitem', verbose_name='수주품목')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_moves_created', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '가발행이동서',
                'verbose_name_plural': '가발행이동서',
                'db_table': 'planned_move_report',
                'ordering': ['po', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='plannedmovereport',
            index=models.Index(fields=['planned_move_no'], name='planned_mov_planned_1a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedmovereport',
            index=models.Index(fields=['status'], name='planned_mov_status_4d5e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedmovereport',
            index=models.Index(fields=['po', 'sequence'], name='planned_mov_po_id_7g8h9i_idx'),
        ),
    ]

