# Generated by Django 5.2.9 on 2025-12-24 12:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCodeSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('FULL', '전체 동기화'), ('INCREMENTAL', '증분 동기화')], max_length=20, verbose_name='동기화 유형')),
                ('started_at', models.DateTimeField(verbose_name='시작 시각')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('records_processed', models.IntegerField(default=0, verbose_name='처리 건수')),
                ('records_created', models.IntegerField(default=0, verbose_name='생성 건수')),
                ('records_updated', models.IntegerField(default=0, verbose_name='수정 건수')),
                ('status', models.CharField(choices=[('RUNNING', '진행중'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='RUNNING', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
            ],
            options={
                'verbose_name': '동기화 로그',
                'verbose_name_plural': '동기화 로그',
                'db_table': 'product_code_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('selection_pattern_code', models.CharField(help_text='FCMS PK (MA_SELECTION_PATTERNS.SELECTION_PATTERN_CODE)', max_length=50, primary_key=True, serialize=False, verbose_name='Selection Pattern Code')),
                ('trade_condition_no', models.CharField(db_index=True, help_text='TRADE_CONDITION_NO (예: KF001, KF013)', max_length=50, verbose_name='제품코드')),
                ('primary_store_user_code', models.CharField(default='KDKK', help_text='PRIMARY_STORE_USER_CODE (우리 고객, 현재 KDKK만)', max_length=50, verbose_name='고객코드')),
                ('customer_user_code', models.CharField(blank=True, help_text='CUSTOMER_USER_CODE', max_length=100, null=True, verbose_name='엔드유저코드')),
                ('customer_user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='엔드유저명')),
                ('cylinder_spec_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='용기스펙코드')),
                ('valve_spec_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='밸브스펙코드')),
                ('gas_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='가스명')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='용량 (L 또는 kg)')),
                ('cylinder_spec_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='용기스펙명')),
                ('valve_spec_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='밸브스펙명')),
                ('cylinder_type_key', models.CharField(blank=True, db_index=True, help_text='CYNOW 대시보드 용기종류 MD5 해시', max_length=32, null=True, verbose_name='용기종류키')),
                ('display_name', models.CharField(blank=True, help_text='사용자 친화적 이름 (예: COS 25kg CGA330)', max_length=200, null=True, verbose_name='표시명')),
                ('is_active', models.BooleanField(default=True, help_text='비활성화된 제품코드는 목록에서 숨김', verbose_name='활성화')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('fcms_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='FCMS 동기화 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '제품코드',
                'verbose_name_plural': '제품코드',
                'db_table': 'product_code',
                'ordering': ['trade_condition_no'],
                'indexes': [models.Index(fields=['trade_condition_no'], name='product_cod_trade_c_45cc8d_idx'), models.Index(fields=['primary_store_user_code'], name='product_cod_primary_bf1211_idx'), models.Index(fields=['cylinder_type_key'], name='product_cod_cylinde_d924be_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='이 날짜부터 이 단가가 적용됨', verbose_name='적용 시작일')),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='원/kg', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='kg당 단가')),
                ('currency', models.CharField(default='KRW', max_length=10, verbose_name='통화')),
                ('note', models.TextField(blank=True, help_text='예: 2025년 연간 계약 단가', null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productcode', verbose_name='제품코드')),
            ],
            options={
                'verbose_name': '단가 이력',
                'verbose_name_plural': '단가 이력',
                'db_table': 'product_price_history',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['product_code', 'effective_date'], name='product_pri_product_3fd911_idx')],
                'unique_together': {('product_code', 'effective_date')},
            },
        ),
    ]
