# Generated by Django 5.2.9 on 2025-12-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_currency_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='filling_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='충전량 (kg)'),
        ),
    ]
