# Generated by Django 5.2.9 on 2025-12-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_filling_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcode',
            name='cylinder_type_key',
            field=models.CharField(blank=True, db_index=True, help_text='CYNOW 대시보드 용기종류 그룹 키', max_length=200, null=True, verbose_name='용기종류키'),
        ),
    ]
