# Generated by Django 5.2.9 on 2025-12-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_expand_cylinder_type_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcode',
            name='default_currency',
            field=models.CharField(choices=[('KRW', '원 (₩)'), ('JPY', '엔 (¥)'), ('USD', '달러 ($)'), ('CNY', '위안 (¥)')], default='KRW', help_text='이 제품코드의 거래 통화', max_length=10, verbose_name='기본 통화'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='currency',
            field=models.CharField(choices=[('KRW', '원 (₩)'), ('JPY', '엔 (¥)'), ('USD', '달러 ($)'), ('CNY', '위안 (¥)')], default='KRW', max_length=10, verbose_name='통화'),
        ),
    ]
